// src/config/env.js
//
// Central place that resolves "which org and credentials are we running
// against" from environment variables, so nothing else in the framework
// reads process.env directly. Loaded by SalesforceAuth.js and
// SalesforceRestClient.js.
const fs = require('fs');
const path = require('path');
require('dotenv').config(); // populates process.env from .env when running locally; a no-op if .env is absent (e.g. on CI, where the platform injects the vars directly)

// JWT Bearer Flow private key: CI injects the PEM content directly as
// SF_JWT_PRIVATE_KEY (secret manager values are single-line, so literal
// "\n" sequences are un-escaped here); locally it's read from the file
// generated by scripts/generate-jwt-cert.js. The username-password flow this
// replaced is blocked by this org's MFA enforcement (there is no field in
// which to answer a verification challenge) and is unsupported entirely on
// the External Client App model.
function resolveJwtPrivateKey() {
  if (process.env.SF_JWT_PRIVATE_KEY) {
    return process.env.SF_JWT_PRIVATE_KEY.replace(/\\n/g, '\n');
  }
  const keyPath = process.env.SF_JWT_PRIVATE_KEY_PATH
    || path.join(__dirname, '..', '..', '.certs', 'server.key');
  return fs.existsSync(keyPath) ? fs.readFileSync(keyPath, 'utf-8') : undefined;
}

// login.salesforce.com is production/developer edition; test.salesforce.com
// is used for both sandboxes and scratch/UAT orgs. apiVersion is pinned here,
// and bumped deliberately when the org upgrades, so a Salesforce release
// doesn't silently change REST payload shapes underneath the tests.
const ENVIRONMENTS = {
  developer: { loginUrl: 'https://login.salesforce.com', apiVersion: 'v61.0' },
  sandbox:   { loginUrl: 'https://test.salesforce.com',  apiVersion: 'v61.0' },
  uat:       { loginUrl: 'https://test.salesforce.com',  apiVersion: 'v61.0' },
};

// SF_ENV should match the Playwright --project being run (see playwright.config.js).
const target = process.env.SF_ENV || 'developer';

// Flattens the selected environment's loginUrl/apiVersion together with the
// credentials, so consumers (SalesforceAuth, SalesforceRestClient) just do
// `env.loginUrl`, `env.username`, etc. without knowing about ENVIRONMENTS.
module.exports = {
  target,
  ...ENVIRONMENTS[target],
  username: process.env.SF_USERNAME,
  consumerKey: process.env.SF_CONSUMER_KEY,
  jwtPrivateKey: resolveJwtPrivateKey(),
};
